
--DDL Tablespace creation

CREATE TABLESPACE "MEME_DATA" DATAFILE 'MEME_DATA.dat'
SIZE 10M
REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

-- DBA DIRECTORY creation

DROP DIRECTORY MEME_IMAGE_DIR;
CREATE OR REPLACE DIRECTORY MEME_IMAGE_DIR AS 'C:\Users\pmanoj\Documents\memesters';

--SEQUENCE creation
DROP SEQUENCE SYSTEM.USER_ID_SEQ;

CREATE SEQUENCE SYSTEM.USER_ID_SEQ
 START WITH     1
 MINVALUE       1
 MAXVALUE       999999999999999999999999999999
 INCREMENT BY   1
 CACHE 100
 CYCLE;

CREATE OR REPLACE PUBLIC SYNONYM USER_ID_SEQ FOR SYSTEM.USER_ID_SEQ;

--TABLE Creation

--MEME USERS
DROP TABLE SYSTEM.MEME_USERS CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.MEME_USERS
(
  USER_ID          NUMBER(30)     NOT NULL,
  USER_NAME        VARCHAR2(200)  NOT NULL,
  PASSWORD         VARCHAR2(500)  NOT NULL,
  FIRST_NAME       VARCHAR2(200)  NOT NULL,
  LAST_NAME        VARCHAR2(200)  NOT NULL,
  EMAIL_ID         VARCHAR2(4000) NOT NULL,
  CREATE_ID        VARCHAR2(30),
  CREATE_DATETIME  DATE,
  UPDATE_ID        VARCHAR2(30),
  UPDATE_DATETIME  DATE
)
TABLESPACE MEME_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MEME_USERS FOR SYSTEM.MEME_USERS;


--MEME_USER_DATA
DROP TABLE SYSTEM.MEME_USER_DATA CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.MEME_USER_DATA
(
  USER_ID          NUMBER(30)     NOT NULL,
  HASH_TAG         VARCHAR2(200)  NOT NULL,
  MEME_DATA        BFILE          NOT NULL,
  CREATE_ID        VARCHAR2(30),
  CREATE_DATETIME  DATE,
  UPDATE_ID        VARCHAR2(30),
  UPDATE_DATETIME  DATE
)
TABLESPACE MEME_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MEME_USER_DATA FOR SYSTEM.MEME_USER_DATA;
